package engine

import "searxgo/internal/models"

// devScienceEngines contains IT, Code, and Science engines
var devScienceEngines = []EngineDefinition{
	{
		ID:                 "alpine_linux_packages",
		DisplayName:        "alpine linux packages",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!alp",
		Homepage:           "https://www.alpinelinux.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.alpinelinux.org",
	},
	{
		ID:                 "cachy_os_packages",
		DisplayName:        "cachy os packages",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!cos",
		Homepage:           "https://cachyos.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://cachyos.org",
	},
	{
		ID:                 "docker_hub",
		DisplayName:        "docker hub",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!dh",
		Homepage:           "https://hub.docker.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://hub.docker.com",
	},
	{
		ID:                 "hex",
		DisplayName:        "hex",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!hex",
		Homepage:           "https://hex.pm/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://hex.pm/",
	},
	{
		ID:                 "hoogle",
		DisplayName:        "hoogle",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!ho",
		Homepage:           "https://hoogle.haskell.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://hoogle.haskell.org/",
	},
	{
		ID:                 "metacpan",
		DisplayName:        "metacpan",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!cpan",
		Homepage:           "https://metacpan.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://metacpan.org/",
	},
	{
		ID:                 "npm",
		DisplayName:        "npm",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!npm",
		Homepage:           "https://npms.io/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://npms.io/",
	},
	{
		ID:                 "packagist",
		DisplayName:        "packagist",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!pack",
		Homepage:           "https://packagist.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://packagist.org",
	},
	{
		ID:                 "pypi",
		DisplayName:        "pypi",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!pypi",
		Homepage:           "https://pypi.org",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pypi.org",
	},
	{
		ID:                 "rubygems",
		DisplayName:        "rubygems",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!rbg",
		Homepage:           "https://rubygems.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://rubygems.org/",
	},
	{
		ID:                 "voidlinux",
		DisplayName:        "voidlinux",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!void",
		Homepage:           "https://voidlinux.org/packages/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://voidlinux.org/packages/",
	},
	{
		ID:                 "askubuntu",
		DisplayName:        "askubuntu",
		Category:           models.CategoryIT,
		Group:              "q&a",
		Shortcut:           "!ubuntu",
		Homepage:           "https://stackexchange.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stackexchange.com",
	},
	{
		ID:                 "stackoverflow",
		DisplayName:        "stackoverflow",
		Category:           models.CategoryIT,
		Group:              "q&a",
		Shortcut:           "!st",
		Homepage:           "https://stackexchange.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stackexchange.com",
	},
	{
		ID:                 "superuser",
		DisplayName:        "superuser",
		Category:           models.CategoryIT,
		Group:              "q&a",
		Shortcut:           "!su",
		Homepage:           "https://stackexchange.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stackexchange.com",
	},
	{
		ID:                 "bitbucket",
		DisplayName:        "bitbucket",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!bb",
		Homepage:           "https://bitbucket.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://bitbucket.org/",
	},
	{
		ID:                 "codeberg",
		DisplayName:        "codeberg",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!cb",
		Homepage:           "https://about.gitea.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://about.gitea.com",
	},
	{
		ID:                 "github",
		DisplayName:        "github",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!gh",
		Homepage:           "https://github.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://github.com/",
	},
	{
		ID:                 "gitlab",
		DisplayName:        "gitlab",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!gl",
		Homepage:           "https://gitlab.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://gitlab.com/",
	},
	{
		ID:                 "huggingface",
		DisplayName:        "huggingface",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!hf",
		Homepage:           "https://huggingface.co/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://huggingface.co/",
	},
	{
		ID:                 "huggingface_datasets",
		DisplayName:        "huggingface datasets",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!hfd",
		Homepage:           "https://huggingface.co/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://huggingface.co/",
	},
	{
		ID:                 "huggingface_spaces",
		DisplayName:        "huggingface spaces",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!hfs",
		Homepage:           "https://huggingface.co/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://huggingface.co/",
	},
	{
		ID:                 "ollama",
		DisplayName:        "ollama",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!ollama",
		Homepage:           "https://ollama.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://ollama.com",
	},
	{
		ID:                 "sourcehut",
		DisplayName:        "sourcehut",
		Category:           models.CategoryIT,
		Group:              "repos",
		Shortcut:           "!srht",
		Homepage:           "https://sourcehut.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://sourcehut.org",
	},
	{
		ID:                 "arch_linux_wiki",
		DisplayName:        "arch linux wiki",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!al",
		Homepage:           "https://wiki.archlinux.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://wiki.archlinux.org/",
	},
	{
		ID:                 "free_software_directory",
		DisplayName:        "free software directory",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!fsd",
		Homepage:           "https://directory.fsf.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://directory.fsf.org/",
	},
	{
		ID:                 "gentoo",
		DisplayName:        "gentoo",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!ge",
		Homepage:           "",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "",
	},
	{
		ID:                 "nixos_wiki",
		DisplayName:        "nixos wiki",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!nixw",
		Homepage:           "",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "",
	},
	{
		ID:                 "anaconda",
		DisplayName:        "anaconda",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!conda",
		Homepage:           "https://anaconda.org/search",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://anaconda.org/search",
	},
	{
		ID:                 "habrahabr",
		DisplayName:        "habrahabr",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!habr",
		Homepage:           "https://habr.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://habr.com/",
	},
	{
		ID:                 "hackernews",
		DisplayName:        "hackernews",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!hn",
		Homepage:           "https://news.ycombinator.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://news.ycombinator.com/",
	},
	{
		ID:                 "mankier",
		DisplayName:        "mankier",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!man",
		Homepage:           "https://www.mankier.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.mankier.com/",
	},
	{
		ID:                 "mdn",
		DisplayName:        "mdn",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!mdn",
		Homepage:           "https://developer.mozilla.org",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://developer.mozilla.org",
	},
	{
		ID:                 "microsoft_learn",
		DisplayName:        "microsoft learn",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!msl",
		Homepage:           "https://learn.microsoft.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://learn.microsoft.com",
	},
	{
		ID:                 "national_vulnerability_database",
		DisplayName:        "national vulnerability database",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!nvd",
		Homepage:           "https://nvd.nist.gov",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://nvd.nist.gov",
	},
	{
		ID:                 "baidu_kaifa",
		DisplayName:        "baidu kaifa",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!bdk",
		Homepage:           "https://www.baidu.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.baidu.com",
	},
	{
		ID:                 "arxiv",
		DisplayName:        "arxiv",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!arx",
		Homepage:           "https://arxiv.org",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://arxiv.org",
	},
	{
		ID:                 "crossref",
		DisplayName:        "crossref",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!cr",
		Homepage:           "https://www.crossref.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.crossref.org/",
	},
	{
		ID:                 "google_scholar",
		DisplayName:        "google scholar",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!gos",
		Homepage:           "https://scholar.google.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://scholar.google.com",
	},
	{
		ID:                 "openalex",
		DisplayName:        "openalex",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!oa",
		Homepage:           "https://openalex.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://openalex.org/",
	},
	{
		ID:                 "pubmed",
		DisplayName:        "pubmed",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!pub",
		Homepage:           "https://www.ncbi.nlm.nih.gov/pubmed/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ncbi.nlm.nih.gov/pubmed/",
	},
	{
		ID:                 "semantic_scholar",
		DisplayName:        "semantic scholar",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!se",
		Homepage:           "https://www.semanticscholar.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.semanticscholar.org/",
	},
	{
		ID:                 "wikispecies",
		DisplayName:        "wikispecies",
		Category:           models.CategoryScience,
		Group:              "wikimedia",
		Shortcut:           "!wsp",
		Homepage:           "https://species.wikimedia.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://species.wikimedia.org/",
	},
	{
		ID:                 "openairedatasets",
		DisplayName:        "openairedatasets",
		Category:           models.CategoryScience,
		Group:              "without further subgrouping",
		Shortcut:           "!oad",
		Homepage:           "https://www.openaire.eu/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.openaire.eu/",
	},
	{
		ID:                 "openairepublications",
		DisplayName:        "openairepublications",
		Category:           models.CategoryScience,
		Group:              "without further subgrouping",
		Shortcut:           "!oap",
		Homepage:           "https://www.openaire.eu/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.openaire.eu/",
	},
	{
		ID:                 "pdbe",
		DisplayName:        "pdbe",
		Category:           models.CategoryScience,
		Group:              "without further subgrouping",
		Shortcut:           "!pdb",
		Homepage:           "https://www.ebi.ac.uk/pdbe",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ebi.ac.uk/pdbe",
	},
	{
		ID:                 "astrophysics_data_system",
		DisplayName:        "astrophysics data system",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!ads",
		Homepage:           "https://ui.adsabs.harvard.edu",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://ui.adsabs.harvard.edu",
	},
	{
		ID:                 "azure",
		DisplayName:        "azure",
		Category:           models.CategoryIT,
		Group:              "cloud",
		Shortcut:           "!az",
		Homepage:           "https://learn.microsoft.com/azure/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://learn.microsoft.com/azure/",
	},
	{
		ID:                 "base",
		DisplayName:        "base",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!base",
		Homepage:           "https://www.base-search.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://www.base-search.net",
	},
	{
		ID:                 "cachy_os",
		DisplayName:        "cachy os",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!cachy",
		Homepage:           "https://wiki.cachyos.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://wiki.cachyos.org",
	},
	{
		ID:                 "cloudflareai",
		DisplayName:        "cloudflareai",
		Category:           models.CategoryIT,
		Group:              "cloud",
		Shortcut:           "!cfai",
		Homepage:           "https://developers.cloudflare.com/workers-ai/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://developers.cloudflare.com/workers-ai/",
	},
	{
		ID:                 "core",
		DisplayName:        "core.ac.uk",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!cor",
		Homepage:           "https://core.ac.uk",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://core.ac.uk",
	},
	{
		ID:                 "crates",
		DisplayName:        "crates.io",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!crates",
		Homepage:           "https://crates.io",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://crates.io",
	},
	{
		ID:                 "discourse",
		DisplayName:        "discourse",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!disc",
		Homepage:           "https://www.discourse.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.discourse.org",
	},
	{
		ID:                 "doku",
		DisplayName:        "dokuwiki",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!doku",
		Homepage:           "https://www.dokuwiki.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.dokuwiki.org",
	},
	{
		ID:                 "europepmc",
		DisplayName:        "europe pmc",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!epmc",
		Homepage:           "https://europepmc.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://europepmc.org",
	},
	{
		ID:                 "gitea",
		DisplayName:        "gitea",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!gitea",
		Homepage:           "https://gitea.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://gitea.com",
	},
	{
		ID:                 "github_code",
		DisplayName:        "github code",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!ghc",
		Homepage:           "https://github.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://github.com",
	},
	{
		ID:                 "google_play",
		DisplayName:        "google play",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!gp",
		Homepage:           "https://play.google.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://play.google.com",
	},
	{
		ID:                 "lib_rs",
		DisplayName:        "lib.rs",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!librs",
		Homepage:           "https://lib.rs",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lib.rs",
	},
	{
		ID:                 "mrs",
		DisplayName:        "mrs",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!mrs",
		Homepage:           "https://mrs.cmbi.umcn.nl",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://mrs.cmbi.umcn.nl",
	},
	{
		ID:                 "nvd",
		DisplayName:        "nvd cve",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!nvd",
		Homepage:           "https://nvd.nist.gov",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://nvd.nist.gov",
	},
	{
		ID:                 "pkg_go_dev",
		DisplayName:        "pkg.go.dev",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!pkg",
		Homepage:           "https://pkg.go.dev",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pkg.go.dev",
	},
	{
		ID:                 "repology",
		DisplayName:        "repology",
		Category:           models.CategoryIT,
		Group:              "packages",
		Shortcut:           "!repo",
		Homepage:           "https://repology.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://repology.org",
	},
	{
		ID:                 "scanr_structures",
		DisplayName:        "scanr structures",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!scanr",
		Homepage:           "https://scanr.enseignementsup-recherche.gouv.fr",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://scanr.enseignementsup-recherche.gouv.fr",
	},
	{
		ID:                 "selfhst",
		DisplayName:        "selfhst directory",
		Category:           models.CategoryIT,
		Group:              "software wikis",
		Shortcut:           "!selfhst",
		Homepage:           "https://selfh.st/apps/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://selfh.st/apps/",
	},
	{
		ID:                 "springer",
		DisplayName:        "springer link",
		Category:           models.CategoryScience,
		Group:              "scientific publications",
		Shortcut:           "!springer",
		Homepage:           "https://link.springer.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://link.springer.com",
	},
	{
		ID:                 "stackexchange",
		DisplayName:        "stackexchange",
		Category:           models.CategoryIT,
		Group:              "without further subgrouping",
		Shortcut:           "!se",
		Homepage:           "https://stackexchange.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stackexchange.com",
	},
}
