package engine

import "searxgo/internal/models"

// generalEngines contains General and News engines
var generalEngines = []EngineDefinition{
	{
		ID:                 "marginalia",
		DisplayName:        "marginalia",
		Category:           models.CategoryGeneral,
		Group:              "blogs",
		Shortcut:           "!mar",
		Homepage:           "https://marginalia.nu",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://marginalia.nu",
	},
	{
		ID:                 "searchmysite",
		DisplayName:        "searchmysite",
		Category:           models.CategoryGeneral,
		Group:              "blogs",
		Shortcut:           "!sms",
		Homepage:           "https://searchmysite.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://searchmysite.net",
	},
	{
		ID:                 "wiby",
		DisplayName:        "wiby",
		Category:           models.CategoryGeneral,
		Group:              "blogs",
		Shortcut:           "!wib",
		Homepage:           "https://wiby.me/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://wiby.me/",
	},
	{
		ID:                 "openlibrary",
		DisplayName:        "openlibrary",
		Category:           models.CategoryGeneral,
		Group:              "books",
		Shortcut:           "!ol",
		Homepage:           "https://openlibrary.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://openlibrary.org",
	},
	{
		ID:                 "currency",
		DisplayName:        "currency",
		Category:           models.CategoryGeneral,
		Group:              "currency",
		Shortcut:           "!cc",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "boardreader",
		DisplayName:        "boardreader",
		Category:           models.CategoryGeneral,
		Group:              "social media",
		Shortcut:           "!boa",
		Homepage:           "https://boardreader.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://boardreader.com",
	},
	{
		ID:                 "dictzone",
		DisplayName:        "dictzone",
		Category:           models.CategoryGeneral,
		Group:              "translate",
		Shortcut:           "!dc",
		Homepage:           "https://dictzone.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://dictzone.com/",
	},
	{
		ID:                 "lingva",
		DisplayName:        "lingva",
		Category:           models.CategoryGeneral,
		Group:              "translate",
		Shortcut:           "!lv",
		Homepage:           "https://github.com/thedaviddelta/lingva-translate",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://github.com/thedaviddelta/lingva-translate",
	},
	{
		ID:                 "mozhi",
		DisplayName:        "mozhi",
		Category:           models.CategoryGeneral,
		Group:              "translate",
		Shortcut:           "!mz",
		Homepage:           "https://codeberg.org/aryak/mozhi",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://codeberg.org/aryak/mozhi",
	},
	{
		ID:                 "mymemory_translated",
		DisplayName:        "mymemory translated",
		Category:           models.CategoryGeneral,
		Group:              "translate",
		Shortcut:           "!tl",
		Homepage:           "https://mymemory.translated.net/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://mymemory.translated.net/",
	},
	{
		ID:                 "bing",
		DisplayName:        "bing",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!bi",
		Homepage:           "https://www.bing.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bing.com",
	},
	{
		ID:                 "brave",
		DisplayName:        "brave",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!br",
		Homepage:           "https://search.brave.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.brave.com/",
	},
	{
		ID:                 "duckduckgo",
		DisplayName:        "duckduckgo",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!ddg",
		Homepage:           "https://lite.duckduckgo.com/lite/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lite.duckduckgo.com/lite/",
	},
	{
		ID:                 "google",
		DisplayName:        "google",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!go",
		Homepage:           "https://www.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.google.com",
	},
	{
		ID:                 "google_cse",
		DisplayName:        "google cse",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!goc",
		Homepage:           "https://www.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.google.com",
	},
	{
		ID:                 "mojeek",
		DisplayName:        "mojeek",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!mjk",
		Homepage:           "https://mojeek.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://mojeek.com",
	},
	{
		ID:                 "qwant",
		DisplayName:        "qwant",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!qw",
		Homepage:           "https://www.qwant.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.qwant.com/",
	},
	{
		ID:                 "startpage",
		DisplayName:        "startpage",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!sp",
		Homepage:           "https://startpage.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://startpage.com",
	},
	{
		ID:                 "yahoo",
		DisplayName:        "yahoo",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!yh",
		Homepage:           "https://search.yahoo.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.yahoo.com/",
	},
	{
		ID:                 "seznam",
		DisplayName:        "seznam",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!szn",
		Homepage:           "https://www.seznam.cz/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.seznam.cz/",
	},
	{
		ID:                 "naver",
		DisplayName:        "naver",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!nvr",
		Homepage:           "https://search.naver.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.naver.com",
	},
	{
		ID:                 "wikibooks",
		DisplayName:        "wikibooks",
		Category:           models.CategoryGeneral,
		Group:              "wikimedia",
		Shortcut:           "!wb",
		Homepage:           "https://www.wikibooks.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikibooks.org/",
	},
	{
		ID:                 "wikiquote",
		DisplayName:        "wikiquote",
		Category:           models.CategoryGeneral,
		Group:              "wikimedia",
		Shortcut:           "!wq",
		Homepage:           "https://www.wikiquote.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikiquote.org/",
	},
	{
		ID:                 "wikisource",
		DisplayName:        "wikisource",
		Category:           models.CategoryGeneral,
		Group:              "wikimedia",
		Shortcut:           "!ws",
		Homepage:           "https://www.wikisource.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikisource.org/",
	},
	{
		ID:                 "wikiversity",
		DisplayName:        "wikiversity",
		Category:           models.CategoryGeneral,
		Group:              "wikimedia",
		Shortcut:           "!wv",
		Homepage:           "https://www.wikiversity.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikiversity.org/",
	},
	{
		ID:                 "wikivoyage",
		DisplayName:        "wikivoyage",
		Category:           models.CategoryGeneral,
		Group:              "wikimedia",
		Shortcut:           "!wy",
		Homepage:           "https://www.wikivoyage.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikivoyage.org/",
	},
	{
		ID:                 "ayo",
		DisplayName:        "ayo",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!ayo",
		Homepage:           "https://serach.ayo.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://serach.ayo.de",
	},
	{
		ID:                 "crowdview",
		DisplayName:        "crowdview",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!cv",
		Homepage:           "https://crowdview.ai/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://crowdview.ai/",
	},
	{
		ID:                 "ddg_definitions",
		DisplayName:        "ddg definitions",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!ddd",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "dogpile",
		DisplayName:        "dogpile",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!dog",
		Homepage:           "https://www.dogpile.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.dogpile.com",
	},
	{
		ID:                 "duckduckgo_web",
		DisplayName:        "duckduckgo web",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!ddgw",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "encyclosearch",
		DisplayName:        "encyclosearch",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!es",
		Homepage:           "https://encyclosearch.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://encyclosearch.org",
	},
	{
		ID:                 "fastbot",
		DisplayName:        "fastbot",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!fa",
		Homepage:           "https://fastbot.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fastbot.de",
	},
	{
		ID:                 "fireball",
		DisplayName:        "fireball",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!fire",
		Homepage:           "https://fireball.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fireball.com",
	},
	{
		ID:                 "fynd",
		DisplayName:        "fynd",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!fynd",
		Homepage:           "https://fynd.bot",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fynd.bot",
	},
	{
		ID:                 "gabanza",
		DisplayName:        "gabanza",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!gab",
		Homepage:           "https://www.gabanza.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.gabanza.com",
	},
	{
		ID:                 "gmx",
		DisplayName:        "gmx",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!gmx",
		Homepage:           "https://search.gmx.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.gmx.com",
	},
	{
		ID:                 "iseek",
		DisplayName:        "iseek",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!isk",
		Homepage:           "https://www.iseek.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.iseek.com",
	},
	{
		ID:                 "luxxle",
		DisplayName:        "luxxle",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!lux",
		Homepage:           "https://luxxle.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://luxxle.com",
	},
	{
		ID:                 "mwmbl",
		DisplayName:        "mwmbl",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!mwm",
		Homepage:           "https://github.com/mwmbl/mwmbl",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://github.com/mwmbl/mwmbl",
	},
	{
		ID:                 "privacywall",
		DisplayName:        "privacywall",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!pw",
		Homepage:           "https://privacywall.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://privacywall.org",
	},
	{
		ID:                 "resulthunter",
		DisplayName:        "resulthunter",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!reh",
		Homepage:           "https://resulthunter.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://resulthunter.com",
	},
	{
		ID:                 "swisscows",
		DisplayName:        "swisscows",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!sw",
		Homepage:           "https://swisscows.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://swisscows.com",
	},
	{
		ID:                 "tineye",
		DisplayName:        "tineye",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!tin",
		Homepage:           "https://tineye.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tineye.com",
	},
	{
		ID:                 "tusksearch",
		DisplayName:        "tusksearch",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!tu",
		Homepage:           "https://tusksearch.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tusksearch.com",
	},
	{
		ID:                 "vuhuv",
		DisplayName:        "vuhuv",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!vu",
		Homepage:           "https://vuhuv.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://vuhuv.com",
	},
	{
		ID:                 "wikidata",
		DisplayName:        "wikidata",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!wd",
		Homepage:           "https://wikidata.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://wikidata.org/",
	},
	{
		ID:                 "wikipedia",
		DisplayName:        "wikipedia",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!wp",
		Homepage:           "https://www.wikipedia.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikipedia.org/",
	},
	{
		ID:                 "wolframalpha",
		DisplayName:        "wolframalpha",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!wa",
		Homepage:           "https://www.wolframalpha.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wolframalpha.com/",
	},
	{
		ID:                 "yacy",
		DisplayName:        "yacy",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!ya",
		Homepage:           "https://yacy.net/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://yacy.net/",
	},
	{
		ID:                 "yandex",
		DisplayName:        "yandex",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!yd",
		Homepage:           "https://yandex.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://yandex.com/",
	},
	{
		ID:                 "yep",
		DisplayName:        "yep",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!yep",
		Homepage:           "https://yep.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://yep.com/",
	},
	{
		ID:                 "zapmeta",
		DisplayName:        "zapmeta",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!zpm",
		Homepage:           "https://www.zapmeta.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.zapmeta.com/",
	},
	{
		ID:                 "searchch",
		DisplayName:        "searchch",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!sch",
		Homepage:           "https://search.ch/web",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.ch/web",
	},
	{
		ID:                 "bpb",
		DisplayName:        "bpb",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!bpb",
		Homepage:           "https://www.bpb.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bpb.de",
	},
	{
		ID:                 "reloado",
		DisplayName:        "reloado",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!rel",
		Homepage:           "https://reloado.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://reloado.com/",
	},
	{
		ID:                 "wikimini",
		DisplayName:        "wikimini",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!wkmn",
		Homepage:           "https://wikimini.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://wikimini.org/",
	},
	{
		ID:                 "abcnyheter",
		DisplayName:        "abcnyheter",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!abc",
		Homepage:           "https://abcnyheter.no",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://abcnyheter.no",
	},
	{
		ID:                 "360search",
		DisplayName:        "360search",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!360so",
		Homepage:           "https://www.so.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.so.com/",
	},
	{
		ID:                 "baidu",
		DisplayName:        "baidu",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!bd",
		Homepage:           "https://www.baidu.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.baidu.com",
	},
	{
		ID:                 "quark",
		DisplayName:        "quark",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!qk",
		Homepage:           "https://quark.sm.cn/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://quark.sm.cn/",
	},
	{
		ID:                 "sogou",
		DisplayName:        "sogou",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!sogou",
		Homepage:           "https://www.sogou.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.sogou.com/",
	},
	{
		ID:                 "mojeek_news",
		DisplayName:        "mojeek news",
		Category:           models.CategoryNews,
		Group:              "web",
		Shortcut:           "!mjknews",
		Homepage:           "https://mojeek.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://mojeek.com",
	},
	{
		ID:                 "startpage_news",
		DisplayName:        "startpage news",
		Category:           models.CategoryNews,
		Group:              "web",
		Shortcut:           "!spn",
		Homepage:           "https://startpage.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://startpage.com",
	},
	{
		ID:                 "wikinews",
		DisplayName:        "wikinews",
		Category:           models.CategoryNews,
		Group:              "wikimedia",
		Shortcut:           "!wn",
		Homepage:           "https://www.wikinews.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wikinews.org/",
	},
	{
		ID:                 "bing_news",
		DisplayName:        "bing news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!bin",
		Homepage:           "https://www.bing.com/news",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bing.com/news",
	},
	{
		ID:                 "duckduckgo_news",
		DisplayName:        "duckduckgo news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!ddn",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "fireball_news",
		DisplayName:        "fireball news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!firen",
		Homepage:           "https://fireball.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fireball.com",
	},
	{
		ID:                 "google_news",
		DisplayName:        "google news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!gon",
		Homepage:           "https://www.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.google.com",
	},
	{
		ID:                 "qwant_news",
		DisplayName:        "qwant news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!qwn",
		Homepage:           "https://www.qwant.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.qwant.com/",
	},
	{
		ID:                 "reuters",
		DisplayName:        "reuters",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!reu",
		Homepage:           "https://www.reuters.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.reuters.com",
	},
	{
		ID:                 "tusksearch_news",
		DisplayName:        "tusksearch news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!tun",
		Homepage:           "https://tusksearch.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tusksearch.com",
	},
	{
		ID:                 "tagesschau",
		DisplayName:        "tagesschau",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!ts",
		Homepage:           "https://tagesschau.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tagesschau.de",
	},
	{
		ID:                 "ansa",
		DisplayName:        "ansa",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!ans",
		Homepage:           "https://www.ansa.it",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ansa.it",
	},
	{
		ID:                 "il_post",
		DisplayName:        "il post",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!pst",
		Homepage:           "https://www.ilpost.it",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ilpost.it",
	},
	{
		ID:                 "naver_news",
		DisplayName:        "naver news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!nvrn",
		Homepage:           "https://search.naver.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.naver.com",
	},
	{
		ID:                 "sogou_wechat",
		DisplayName:        "sogou wechat",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!sogouw",
		Homepage:           "https://weixin.sogou.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://weixin.sogou.com/",
	},
	{
		ID:                 "ahmia",
		DisplayName:        "ahmia",
		Category:           models.CategoryGeneral,
		Group:              "onions",
		Shortcut:           "!ah",
		Homepage:           "https://ahmia.fi",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            3.0,
		About:              "https://ahmia.fi",
	},
	{
		ID:                 "braveapi",
		DisplayName:        "braveapi",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!bapi",
		Homepage:           "https://brave.com/search/api/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://brave.com/search/api/",
	},
	{
		ID:                 "chatnoir",
		DisplayName:        "chatnoir",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!cn",
		Homepage:           "https://www.chatnoir.eu",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.chatnoir.eu",
	},
	{
		ID:                 "chinaso",
		DisplayName:        "chinaso",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!chinaso",
		Homepage:           "https://www.chinaso.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.chinaso.com",
	},
	{
		ID:                 "currency_convert",
		DisplayName:        "currency convert",
		Category:           models.CategoryGeneral,
		Group:              "currency",
		Shortcut:           "!curr",
		Homepage:           "https://www.xe.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.xe.com",
	},
	{
		ID:                 "exaapi",
		DisplayName:        "exa api",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!exa",
		Homepage:           "https://exa.ai",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://exa.ai",
	},
	{
		ID:                 "grokipedia",
		DisplayName:        "grokipedia",
		Category:           models.CategoryGeneral,
		Group:              "encyclopedias",
		Shortcut:           "!grok",
		Homepage:           "https://grokipedia.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://grokipedia.org",
	},
	{
		ID:                 "jina",
		DisplayName:        "jina ai",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!jina",
		Homepage:           "https://jina.ai",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://jina.ai",
	},
	{
		ID:                 "kagi",
		DisplayName:        "kagi",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!kagi",
		Homepage:           "https://kagi.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://kagi.com",
	},
	{
		ID:                 "keenable",
		DisplayName:        "keenable",
		Category:           models.CategoryGeneral,
		Group:              "blogs",
		Shortcut:           "!keen",
		Homepage:           "https://keenable.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://keenable.org",
	},
	{
		ID:                 "loc",
		DisplayName:        "library of congress",
		Category:           models.CategoryGeneral,
		Group:              "books",
		Shortcut:           "!loc",
		Homepage:           "https://www.loc.gov",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://www.loc.gov",
	},
	{
		ID:                 "mediawiki",
		DisplayName:        "mediawiki",
		Category:           models.CategoryGeneral,
		Group:              "without further subgrouping",
		Shortcut:           "!mw",
		Homepage:           "https://www.mediawiki.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.mediawiki.org",
	},
	{
		ID:                 "neocities",
		DisplayName:        "neocities",
		Category:           models.CategoryGeneral,
		Group:              "blogs",
		Shortcut:           "!neo",
		Homepage:           "https://neocities.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://neocities.org",
	},
	{
		ID:                 "neosearch",
		DisplayName:        "neosearch",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!neos",
		Homepage:           "https://neosearch.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://neosearch.net",
	},
	{
		ID:                 "opensemantic",
		DisplayName:        "open semantic search",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!oss",
		Homepage:           "https://opensemanticsearch.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://opensemanticsearch.org",
	},
	{
		ID:                 "s1search",
		DisplayName:        "s1search",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!s1",
		Homepage:           "https://s1search.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://s1search.com",
	},
	{
		ID:                 "s1search_rampjs",
		DisplayName:        "s1search rampjs",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!s1r",
		Homepage:           "https://s1search.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://s1search.com",
	},
	{
		ID:                 "searchrockit",
		DisplayName:        "searchrockit",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!srock",
		Homepage:           "https://searchrockit.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://searchrockit.com",
	},
	{
		ID:                 "searchzee",
		DisplayName:        "searchzee",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!szee",
		Homepage:           "https://searchzee.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://searchzee.com",
	},
	{
		ID:                 "seekninja",
		DisplayName:        "seekninja",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!sninja",
		Homepage:           "https://seekninja.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://seekninja.com",
	},
	{
		ID:                 "startpagina",
		DisplayName:        "startpagina",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!startp",
		Homepage:           "https://www.startpagina.nl",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.startpagina.nl",
	},
	{
		ID:                 "swisscows_news",
		DisplayName:        "swisscows news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!swn",
		Homepage:           "https://swisscows.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://swisscows.com",
	},
	{
		ID:                 "tiger",
		DisplayName:        "tiger search",
		Category:           models.CategoryGeneral,
		Group:              "web",
		Shortcut:           "!tiger",
		Homepage:           "https://tiger.search",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tiger.search",
	},
	{
		ID:                 "tonline",
		DisplayName:        "t-online",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!tonline",
		Homepage:           "https://www.t-online.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.t-online.de",
	},
	{
		ID:                 "yahoo_news",
		DisplayName:        "yahoo news",
		Category:           models.CategoryNews,
		Group:              "without further subgrouping",
		Shortcut:           "!yn",
		Homepage:           "https://news.yahoo.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://news.yahoo.com",
	},
}
