package engine

import "searxgo/internal/models"

// mediaEngines contains Images, Videos, and Music engines
var mediaEngines = []EngineDefinition{
	{
		ID:                 "devicons",
		DisplayName:        "devicons",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!di",
		Homepage:           "https://devicon.dev/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://devicon.dev/",
	},
	{
		ID:                 "flaticon",
		DisplayName:        "flaticon",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!fli",
		Homepage:           "https://www.flaticon.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.flaticon.com",
	},
	{
		ID:                 "lucide",
		DisplayName:        "lucide",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!luc",
		Homepage:           "https://lucide.dev/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lucide.dev/",
	},
	{
		ID:                 "material_icons",
		DisplayName:        "material icons",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!mi",
		Homepage:           "https://fonts.google.com/icons",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fonts.google.com/icons",
	},
	{
		ID:                 "selfhst_icons",
		DisplayName:        "selfhst icons",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!si",
		Homepage:           "https://selfh.st/icons/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://selfh.st/icons/",
	},
	{
		ID:                 "uxwing",
		DisplayName:        "uxwing",
		Category:           models.CategoryImages,
		Group:              "icons",
		Shortcut:           "!ux",
		Homepage:           "https://uxwing.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://uxwing.com",
	},
	{
		ID:                 "bing_images",
		DisplayName:        "bing images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!bii",
		Homepage:           "https://www.bing.com/images",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bing.com/images",
	},
	{
		ID:                 "google_cse_images",
		DisplayName:        "google cse images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!goci",
		Homepage:           "https://www.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.google.com",
	},
	{
		ID:                 "google_images",
		DisplayName:        "google images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!goi",
		Homepage:           "https://images.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://images.google.com",
	},
	{
		ID:                 "mojeek_images",
		DisplayName:        "mojeek images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!mjkimg",
		Homepage:           "https://mojeek.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://mojeek.com",
	},
	{
		ID:                 "qwant_images",
		DisplayName:        "qwant images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!qwi",
		Homepage:           "https://www.qwant.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.qwant.com/",
	},
	{
		ID:                 "startpage_images",
		DisplayName:        "startpage images",
		Category:           models.CategoryImages,
		Group:              "web",
		Shortcut:           "!spi",
		Homepage:           "https://startpage.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://startpage.com",
	},
	{
		ID:                 "1x",
		DisplayName:        "1x",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!1x",
		Homepage:           "https://1x.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://1x.com/",
	},
	{
		ID:                 "500px",
		DisplayName:        "500px",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!500",
		Homepage:           "https://500px.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://500px.com",
	},
	{
		ID:                 "adobe_stock",
		DisplayName:        "adobe stock",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!asi",
		Homepage:           "https://stock.adobe.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stock.adobe.com/",
	},
	{
		ID:                 "artic",
		DisplayName:        "artic",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!arc",
		Homepage:           "https://www.artic.edu",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.artic.edu",
	},
	{
		ID:                 "artstation",
		DisplayName:        "artstation",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!as",
		Homepage:           "https://www.artstation.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.artstation.com/",
	},
	{
		ID:                 "cara",
		DisplayName:        "cara",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!ca",
		Homepage:           "https://cara.app",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://cara.app",
	},
	{
		ID:                 "dogpile_images",
		DisplayName:        "dogpile images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!dogi",
		Homepage:           "https://www.dogpile.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.dogpile.com",
	},
	{
		ID:                 "duckduckgo_images",
		DisplayName:        "duckduckgo images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!ddi",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "findfiles_images",
		DisplayName:        "findfiles images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!fifi",
		Homepage:           "https://findfiles.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://findfiles.net",
	},
	{
		ID:                 "findthatmeme",
		DisplayName:        "findthatmeme",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!ftm",
		Homepage:           "https://findthatmeme.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://findthatmeme.com",
	},
	{
		ID:                 "flickr",
		DisplayName:        "flickr",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!fl",
		Homepage:           "https://www.flickr.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.flickr.com",
	},
	{
		ID:                 "frinkiac",
		DisplayName:        "frinkiac",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!frk",
		Homepage:           "https://frinkiac.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://frinkiac.com",
	},
	{
		ID:                 "giphy",
		DisplayName:        "giphy",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!gif",
		Homepage:           "https://giphy.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://giphy.com",
	},
	{
		ID:                 "imgur",
		DisplayName:        "imgur",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!img",
		Homepage:           "https://imgur.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://imgur.com/",
	},
	{
		ID:                 "ipernity",
		DisplayName:        "ipernity",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!ip",
		Homepage:           "https://www.ipernity.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ipernity.com",
	},
	{
		ID:                 "library_of_congress",
		DisplayName:        "library of congress",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!loc",
		Homepage:           "https://www.loc.gov/pictures/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.loc.gov/pictures/",
	},
	{
		ID:                 "magnific",
		DisplayName:        "magnific",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!mag",
		Homepage:           "https://www.magnific.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.magnific.com",
	},
	{
		ID:                 "openverse",
		DisplayName:        "openverse",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!opv",
		Homepage:           "https://openverse.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://openverse.org/",
	},
	{
		ID:                 "pexels",
		DisplayName:        "pexels",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pe",
		Homepage:           "https://www.pexels.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.pexels.com",
	},
	{
		ID:                 "picjumbo",
		DisplayName:        "picjumbo",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pj",
		Homepage:           "https://picjumbo.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://picjumbo.com",
	},
	{
		ID:                 "pinterest",
		DisplayName:        "pinterest",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pin",
		Homepage:           "https://www.pinterest.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.pinterest.com/",
	},
	{
		ID:                 "pixabay_images",
		DisplayName:        "pixabay images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pixi",
		Homepage:           "https://pixabay.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pixabay.com",
	},
	{
		ID:                 "privacywall_images",
		DisplayName:        "privacywall images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pwi",
		Homepage:           "https://privacywall.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://privacywall.org",
	},
	{
		ID:                 "public_domain_image_archive",
		DisplayName:        "public domain image archive",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pdia",
		Homepage:           "https://pdimagearchive.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pdimagearchive.org",
	},
	{
		ID:                 "resulthunter_images",
		DisplayName:        "resulthunter images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!rehi",
		Homepage:           "https://resulthunter.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://resulthunter.com",
	},
	{
		ID:                 "shopify_stock",
		DisplayName:        "shopify stock",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!shs",
		Homepage:           "https://www.shopify.com/stock-photos",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.shopify.com/stock-photos",
	},
	{
		ID:                 "sogou_images",
		DisplayName:        "sogou images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!sogoui",
		Homepage:           "https://pic.sogou.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pic.sogou.com/",
	},
	{
		ID:                 "stocksnap",
		DisplayName:        "stocksnap",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!sto",
		Homepage:           "https://stocksnap.io",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stocksnap.io",
	},
	{
		ID:                 "tusksearch_images",
		DisplayName:        "tusksearch images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!tui",
		Homepage:           "https://tusksearch.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tusksearch.com",
	},
	{
		ID:                 "unsplash",
		DisplayName:        "unsplash",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!us",
		Homepage:           "https://unsplash.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://unsplash.com",
	},
	{
		ID:                 "vuhuv_images",
		DisplayName:        "vuhuv images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!vui",
		Homepage:           "https://vuhuv.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://vuhuv.com",
	},
	{
		ID:                 "yacy_images",
		DisplayName:        "yacy images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!yai",
		Homepage:           "https://yacy.net/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://yacy.net/",
	},
	{
		ID:                 "yandex_images",
		DisplayName:        "yandex images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!ydi",
		Homepage:           "https://yandex.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://yandex.com/",
	},
	{
		ID:                 "naver_images",
		DisplayName:        "naver images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!nvri",
		Homepage:           "https://search.naver.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.naver.com",
	},
	{
		ID:                 "baidu_images",
		DisplayName:        "baidu images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!bdi",
		Homepage:           "https://www.baidu.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.baidu.com",
	},
	{
		ID:                 "quark_images",
		DisplayName:        "quark images",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!qki",
		Homepage:           "https://quark.sm.cn/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://quark.sm.cn/",
	},
	{
		ID:                 "bing_videos",
		DisplayName:        "bing videos",
		Category:           models.CategoryVideos,
		Group:              "web",
		Shortcut:           "!biv",
		Homepage:           "https://www.bing.com/videos",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bing.com/videos",
	},
	{
		ID:                 "google_videos",
		DisplayName:        "google videos",
		Category:           models.CategoryVideos,
		Group:              "web",
		Shortcut:           "!gov",
		Homepage:           "https://www.google.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.google.com",
	},
	{
		ID:                 "qwant_videos",
		DisplayName:        "qwant videos",
		Category:           models.CategoryVideos,
		Group:              "web",
		Shortcut:           "!qwv",
		Homepage:           "https://www.qwant.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.qwant.com/",
	},
	{
		ID:                 "360search_videos",
		DisplayName:        "360search videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!360sov",
		Homepage:           "https://tv.360kan.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tv.360kan.com/",
	},
	{
		ID:                 "adobe_stock_video",
		DisplayName:        "adobe stock video",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!asv",
		Homepage:           "https://stock.adobe.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stock.adobe.com/",
	},
	{
		ID:                 "bilibili",
		DisplayName:        "bilibili",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!bil",
		Homepage:           "https://www.bilibili.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.bilibili.com",
	},
	{
		ID:                 "bitchute",
		DisplayName:        "bitchute",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!bit",
		Homepage:           "https://bitchute.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://bitchute.com",
	},
	{
		ID:                 "dailymotion",
		DisplayName:        "dailymotion",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!dm",
		Homepage:           "https://www.dailymotion.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.dailymotion.com",
	},
	{
		ID:                 "duckduckgo_videos",
		DisplayName:        "duckduckgo videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!ddv",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "findfiles_videos",
		DisplayName:        "findfiles videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!fifv",
		Homepage:           "https://findfiles.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://findfiles.net",
	},
	{
		ID:                 "fireball_videos",
		DisplayName:        "fireball videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!firev",
		Homepage:           "https://fireball.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fireball.com",
	},
	{
		ID:                 "google_play_movies",
		DisplayName:        "google play movies",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!gpm",
		Homepage:           "https://play.google.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://play.google.com/",
	},
	{
		ID:                 "odysee",
		DisplayName:        "odysee",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!od",
		Homepage:           "https://odysee.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://odysee.com/",
	},
	{
		ID:                 "peertube",
		DisplayName:        "peertube",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!ptb",
		Homepage:           "https://joinpeertube.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://joinpeertube.org",
	},
	{
		ID:                 "pixabay_videos",
		DisplayName:        "pixabay videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!pixv",
		Homepage:           "https://pixabay.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://pixabay.com",
	},
	{
		ID:                 "privacywall_videos",
		DisplayName:        "privacywall videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!pwv",
		Homepage:           "https://privacywall.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://privacywall.org",
	},
	{
		ID:                 "rumble",
		DisplayName:        "rumble",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!ru",
		Homepage:           "https://rumble.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://rumble.com/",
	},
	{
		ID:                 "sepiasearch",
		DisplayName:        "sepiasearch",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!sep",
		Homepage:           "https://sepiasearch.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://sepiasearch.org",
	},
	{
		ID:                 "tusksearch_videos",
		DisplayName:        "tusksearch videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!tuv",
		Homepage:           "https://tusksearch.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://tusksearch.com",
	},
	{
		ID:                 "vimeo",
		DisplayName:        "vimeo",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!vm",
		Homepage:           "https://vimeo.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://vimeo.com/",
	},
	{
		ID:                 "vuhuv_videos",
		DisplayName:        "vuhuv videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!vuv",
		Homepage:           "https://vuhuv.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://vuhuv.com",
	},
	{
		ID:                 "youtube",
		DisplayName:        "youtube",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!yt",
		Homepage:           "https://www.youtube.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.youtube.com/",
	},
	{
		ID:                 "mediathekviewweb",
		DisplayName:        "mediathekviewweb",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!mvw",
		Homepage:           "https://mediathekviewweb.de/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://mediathekviewweb.de/",
	},
	{
		ID:                 "ina",
		DisplayName:        "ina",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!in",
		Homepage:           "https://www.ina.fr/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ina.fr/",
	},
	{
		ID:                 "niconico",
		DisplayName:        "niconico",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!nico",
		Homepage:           "https://www.nicovideo.jp/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.nicovideo.jp/",
	},
	{
		ID:                 "naver_videos",
		DisplayName:        "naver videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!nvrv",
		Homepage:           "https://search.naver.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://search.naver.com",
	},
	{
		ID:                 "acfun",
		DisplayName:        "acfun",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!acf",
		Homepage:           "https://www.acfun.cn/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.acfun.cn/",
	},
	{
		ID:                 "iqiyi",
		DisplayName:        "iqiyi",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!iq",
		Homepage:           "https://www.iqiyi.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.iqiyi.com/",
	},
	{
		ID:                 "sogou_videos",
		DisplayName:        "sogou videos",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!sogouv",
		Homepage:           "https://v.sogou.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://v.sogou.com/",
	},
	{
		ID:                 "genius",
		DisplayName:        "genius",
		Category:           models.CategoryMusic,
		Group:              "lyrics",
		Shortcut:           "!gen",
		Homepage:           "https://genius.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://genius.com/",
	},
	{
		ID:                 "radio_browser",
		DisplayName:        "radio browser",
		Category:           models.CategoryMusic,
		Group:              "radio",
		Shortcut:           "!rb",
		Homepage:           "https://www.radio-browser.info/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.radio-browser.info/",
	},
	{
		ID:                 "adobe_stock_audio",
		DisplayName:        "adobe stock audio",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!asa",
		Homepage:           "https://stock.adobe.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://stock.adobe.com/",
	},
	{
		ID:                 "bandcamp",
		DisplayName:        "bandcamp",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!bc",
		Homepage:           "https://bandcamp.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://bandcamp.com/",
	},
	{
		ID:                 "deezer",
		DisplayName:        "deezer",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!dz",
		Homepage:           "https://deezer.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://deezer.com",
	},
	{
		ID:                 "findfiles_music",
		DisplayName:        "findfiles music",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!fifm",
		Homepage:           "https://findfiles.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://findfiles.net",
	},
	{
		ID:                 "mixcloud",
		DisplayName:        "mixcloud",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!mc",
		Homepage:           "https://www.mixcloud.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.mixcloud.com/",
	},
	{
		ID:                 "soundcloud",
		DisplayName:        "soundcloud",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!sc",
		Homepage:           "https://soundcloud.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://soundcloud.com",
	},
	{
		ID:                 "yandex_music",
		DisplayName:        "yandex music",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!ydm",
		Homepage:           "https://music.yandex.ru",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://music.yandex.ru",
	},
	{
		ID:                 "youtube_music",
		DisplayName:        "youtube music",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!ytm",
		Homepage:           "https://music.youtube.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://music.youtube.com/",
	},
	{
		ID:                 "ccc_media",
		DisplayName:        "media.ccc.de",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!c3tv",
		Homepage:           "https://media.ccc.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://media.ccc.de",
	},
	{
		ID:                 "deviantart",
		DisplayName:        "deviantart",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!da",
		Homepage:           "https://www.deviantart.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://www.deviantart.com",
	},
	{
		ID:                 "freesound",
		DisplayName:        "freesound",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!fs",
		Homepage:           "https://freesound.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://freesound.org",
	},
	{
		ID:                 "invidious",
		DisplayName:        "invidious",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!inv",
		Homepage:           "https://invidious.io",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://invidious.io",
	},
	{
		ID:                 "openclipart",
		DisplayName:        "openclipart",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!oca",
		Homepage:           "https://openclipart.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://openclipart.org",
	},
	{
		ID:                 "piped",
		DisplayName:        "piped",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!piped",
		Homepage:           "https://piped.video",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://piped.video",
	},
	{
		ID:                 "pixiv",
		DisplayName:        "pixiv",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!pixiv",
		Homepage:           "https://www.pixiv.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://www.pixiv.net",
	},
	{
		ID:                 "spotify",
		DisplayName:        "spotify",
		Category:           models.CategoryMusic,
		Group:              "without further subgrouping",
		Shortcut:           "!spo",
		Homepage:           "https://open.spotify.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://open.spotify.com",
	},
	{
		ID:                 "tubearchivist",
		DisplayName:        "tubearchivist",
		Category:           models.CategoryVideos,
		Group:              "without further subgrouping",
		Shortcut:           "!ta",
		Homepage:           "https://www.tubearchivist.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://www.tubearchivist.com",
	},
	{
		ID:                 "wallhaven",
		DisplayName:        "wallhaven",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!wh",
		Homepage:           "https://wallhaven.cc",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://wallhaven.cc",
	},
	{
		ID:                 "wikicommons",
		DisplayName:        "wikimedia commons",
		Category:           models.CategoryImages,
		Group:              "without further subgrouping",
		Shortcut:           "!commons",
		Homepage:           "https://commons.wikimedia.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://commons.wikimedia.org",
	},
}
