package engine

import "searxgo/internal/models"

// filesOtherEngines contains Files, Social, and Other engines
var filesOtherEngines = []EngineDefinition{
	{
		ID:                 "etymonline",
		DisplayName:        "etymonline",
		Category:           models.CategoryOther,
		Group:              "dictionaries",
		Shortcut:           "!et",
		Homepage:           "https://www.etymonline.com/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.etymonline.com/",
	},
	{
		ID:                 "wiktionary",
		DisplayName:        "wiktionary",
		Category:           models.CategoryOther,
		Group:              "dictionaries",
		Shortcut:           "!wt",
		Homepage:           "https://www.wiktionary.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wiktionary.org/",
	},
	{
		ID:                 "wordnik",
		DisplayName:        "wordnik",
		Category:           models.CategoryOther,
		Group:              "dictionaries",
		Shortcut:           "!wnik",
		Homepage:           "https://www.wordnik.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.wordnik.com",
	},
	{
		ID:                 "duden",
		DisplayName:        "duden",
		Category:           models.CategoryOther,
		Group:              "dictionaries",
		Shortcut:           "!du",
		Homepage:           "https://www.duden.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.duden.de",
	},
	{
		ID:                 "jisho",
		DisplayName:        "jisho",
		Category:           models.CategoryOther,
		Group:              "dictionaries",
		Shortcut:           "!js",
		Homepage:           "https://jisho.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://jisho.org",
	},
	{
		ID:                 "1337x",
		DisplayName:        "1337x",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!1337x",
		Homepage:           "https://1337x.to/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://1337x.to/",
	},
	{
		ID:                 "annas_archive",
		DisplayName:        "annas archive",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!aa",
		Homepage:           "https://annas-archive.gl/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://annas-archive.gl/",
	},
	{
		ID:                 "apk_mirror",
		DisplayName:        "apk mirror",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!apkm",
		Homepage:           "https://www.apkmirror.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.apkmirror.com",
	},
	{
		ID:                 "apple_app_store",
		DisplayName:        "apple app store",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!aps",
		Homepage:           "https://www.apple.com/app-store/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.apple.com/app-store/",
	},
	{
		ID:                 "bt4g",
		DisplayName:        "bt4g",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!bt4g",
		Homepage:           "https://bt4gprx.com",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://bt4gprx.com",
	},
	{
		ID:                 "btdigg",
		DisplayName:        "btdigg",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!bt",
		Homepage:           "https://btdig.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://btdig.com",
	},
	{
		ID:                 "fdroid",
		DisplayName:        "fdroid",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!fd",
		Homepage:           "https://f-droid.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://f-droid.org/",
	},
	{
		ID:                 "findfiles",
		DisplayName:        "findfiles",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!fif",
		Homepage:           "https://findfiles.net",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://findfiles.net",
	},
	{
		ID:                 "google_play_apps",
		DisplayName:        "google play apps",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!gpa",
		Homepage:           "https://play.google.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://play.google.com/",
	},
	{
		ID:                 "kickass",
		DisplayName:        "kickass",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!kc",
		Homepage:           "https://kickasstorrents.to",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://kickasstorrents.to",
	},
	{
		ID:                 "library_genesis",
		DisplayName:        "library genesis",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!lg",
		Homepage:           "https://libgen.fun/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://libgen.fun/",
	},
	{
		ID:                 "nyaa",
		DisplayName:        "nyaa",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!nt",
		Homepage:           "https://nyaa.si/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://nyaa.si/",
	},
	{
		ID:                 "openrepos",
		DisplayName:        "openrepos",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!or",
		Homepage:           "https://openrepos.net/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://openrepos.net/",
	},
	{
		ID:                 "piratebay",
		DisplayName:        "piratebay",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!tpb",
		Homepage:           "https://thepiratebay.org",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://thepiratebay.org",
	},
	{
		ID:                 "solidtorrents",
		DisplayName:        "solidtorrents",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!solid",
		Homepage:           "https://www.solidtorrents.to/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.solidtorrents.to/",
	},
	{
		ID:                 "tokyotoshokan",
		DisplayName:        "tokyotoshokan",
		Category:           models.CategoryOther,
		Group:              "files",
		Shortcut:           "!tt",
		Homepage:           "https://www.tokyotosho.info/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.tokyotosho.info/",
	},
	{
		ID:                 "apple_maps",
		DisplayName:        "apple maps",
		Category:           models.CategoryOther,
		Group:              "map",
		Shortcut:           "!apm",
		Homepage:           "https://www.apple.com/maps/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.apple.com/maps/",
	},
	{
		ID:                 "openstreetmap",
		DisplayName:        "openstreetmap",
		Category:           models.CategoryOther,
		Group:              "map",
		Shortcut:           "!osm",
		Homepage:           "https://www.openstreetmap.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.openstreetmap.org/",
	},
	{
		ID:                 "photon",
		DisplayName:        "photon",
		Category:           models.CategoryOther,
		Group:              "map",
		Shortcut:           "!ph",
		Homepage:           "https://photon.komoot.io",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://photon.komoot.io",
	},
	{
		ID:                 "imdb",
		DisplayName:        "imdb",
		Category:           models.CategoryOther,
		Group:              "movies",
		Shortcut:           "!imdb",
		Homepage:           "https://imdb.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://imdb.com/",
	},
	{
		ID:                 "rottentomatoes",
		DisplayName:        "rottentomatoes",
		Category:           models.CategoryOther,
		Group:              "movies",
		Shortcut:           "!rt",
		Homepage:           "https://www.rottentomatoes.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.rottentomatoes.com/",
	},
	{
		ID:                 "tmdb",
		DisplayName:        "tmdb",
		Category:           models.CategoryOther,
		Group:              "movies",
		Shortcut:           "!tm",
		Homepage:           "",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "",
	},
	{
		ID:                 "moviepilot",
		DisplayName:        "moviepilot",
		Category:           models.CategoryOther,
		Group:              "movies",
		Shortcut:           "!mp",
		Homepage:           "https://www.moviepilot.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.moviepilot.de",
	},
	{
		ID:                 "senscritique",
		DisplayName:        "senscritique",
		Category:           models.CategoryOther,
		Group:              "movies",
		Shortcut:           "!scr",
		Homepage:           "https://www.senscritique.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.senscritique.com/",
	},
	{
		ID:                 "geizhals",
		DisplayName:        "geizhals",
		Category:           models.CategoryOther,
		Group:              "shopping",
		Shortcut:           "!geiz",
		Homepage:           "https://geizhals.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://geizhals.de",
	},
	{
		ID:                 "9gag",
		DisplayName:        "9gag",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!9g",
		Homepage:           "https://9gag.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://9gag.com/",
	},
	{
		ID:                 "lemmy_comments",
		DisplayName:        "lemmy comments",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!lecom",
		Homepage:           "https://lemmy.ml/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lemmy.ml/",
	},
	{
		ID:                 "lemmy_communities",
		DisplayName:        "lemmy communities",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!leco",
		Homepage:           "https://lemmy.ml/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lemmy.ml/",
	},
	{
		ID:                 "lemmy_posts",
		DisplayName:        "lemmy posts",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!lepo",
		Homepage:           "https://lemmy.ml/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lemmy.ml/",
	},
	{
		ID:                 "lemmy_users",
		DisplayName:        "lemmy users",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!leus",
		Homepage:           "https://lemmy.ml/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://lemmy.ml/",
	},
	{
		ID:                 "mastodon_hashtags",
		DisplayName:        "mastodon hashtags",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!mah",
		Homepage:           "https://joinmastodon.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://joinmastodon.org/",
	},
	{
		ID:                 "mastodon_users",
		DisplayName:        "mastodon users",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!mau",
		Homepage:           "https://joinmastodon.org/",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://joinmastodon.org/",
	},
	{
		ID:                 "tootfinder",
		DisplayName:        "tootfinder",
		Category:           models.CategoryOther,
		Group:              "social media",
		Shortcut:           "!toot",
		Homepage:           "https://www.tootfinder.ch",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.tootfinder.ch",
	},
	{
		ID:                 "minecraft_wiki",
		DisplayName:        "minecraft wiki",
		Category:           models.CategoryOther,
		Group:              "software wikis",
		Shortcut:           "!mcw",
		Homepage:           "https://minecraft.wiki/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://minecraft.wiki/",
	},
	{
		ID:                 "duckduckgo_weather",
		DisplayName:        "duckduckgo weather",
		Category:           models.CategoryOther,
		Group:              "weather",
		Shortcut:           "!ddw",
		Homepage:           "https://duckduckgo.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://duckduckgo.com/",
	},
	{
		ID:                 "openmeteo",
		DisplayName:        "openmeteo",
		Category:           models.CategoryOther,
		Group:              "weather",
		Shortcut:           "!om",
		Homepage:           "https://open-meteo.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://open-meteo.com",
	},
	{
		ID:                 "emojipedia",
		DisplayName:        "emojipedia",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!em",
		Homepage:           "https://emojipedia.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://emojipedia.org",
	},
	{
		ID:                 "erowid",
		DisplayName:        "erowid",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!ew",
		Homepage:           "https://www.erowid.org/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.erowid.org/",
	},
	{
		ID:                 "fyyd",
		DisplayName:        "fyyd",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!fy",
		Homepage:           "https://fyyd.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://fyyd.de",
	},
	{
		ID:                 "goodreads",
		DisplayName:        "goodreads",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!good",
		Homepage:           "https://www.goodreads.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.goodreads.com",
	},
	{
		ID:                 "podchaser",
		DisplayName:        "podchaser",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!poc",
		Homepage:           "https://www.podchaser.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.podchaser.com",
	},
	{
		ID:                 "steam",
		DisplayName:        "steam",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!stm",
		Homepage:           "https://store.steampowered.com/",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://store.steampowered.com/",
	},
	{
		ID:                 "chefkoch",
		DisplayName:        "chefkoch",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!chef",
		Homepage:           "https://www.chefkoch.de",
		DefaultEnabled:     false,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.chefkoch.de",
	},
	{
		ID:                 "destatis",
		DisplayName:        "destatis",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!destat",
		Homepage:           "https://www.destatis.de",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.destatis.de",
	},
	{
		ID:                 "digbt",
		DisplayName:        "digbt",
		Category:           models.CategoryFiles,
		Group:              "torrents",
		Shortcut:           "!digbt",
		Homepage:           "https://digbt.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://digbt.org",
	},
	{
		ID:                 "ebay",
		DisplayName:        "ebay",
		Category:           models.CategoryOther,
		Group:              "without further subgrouping",
		Shortcut:           "!eb",
		Homepage:           "https://www.ebay.com",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.0,
		About:              "https://www.ebay.com",
	},
	{
		ID:                 "lemmy",
		DisplayName:        "lemmy",
		Category:           models.CategorySocial,
		Group:              "social media",
		Shortcut:           "!lemmy",
		Homepage:           "https://join-lemmy.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://join-lemmy.org",
	},
	{
		ID:                 "mastodon",
		DisplayName:        "mastodon",
		Category:           models.CategorySocial,
		Group:              "social media",
		Shortcut:           "!mastodon",
		Homepage:           "https://joinmastodon.org",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            2.5,
		About:              "https://joinmastodon.org",
	},
	{
		ID:                 "torznab",
		DisplayName:        "torznab",
		Category:           models.CategoryFiles,
		Group:              "torrents",
		Shortcut:           "!tz",
		Homepage:           "https://torznab.github.io",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            3.0,
		About:              "https://torznab.github.io",
	},
	{
		ID:                 "zlibrary",
		DisplayName:        "z-library",
		Category:           models.CategoryFiles,
		Group:              "books",
		Shortcut:           "!zlib",
		Homepage:           "https://z-library.se",
		DefaultEnabled:     true,
		SupportsSafeSearch: false,
		SupportsTimeRange:  false,
		Weight:             1.0,
		MaxTime:            3.0,
		About:              "https://z-library.se",
	},}
